import React from 'react';
import {AbsoluteFill, interpolate, spring, useCurrentFrame, useVideoConfig} from 'remotion';
import core from '../content/case001.json';
import {DISPLAY_FONT,TEXT_FONT} from '../fonts';
import {Narration,duckAt,type VoiceMark} from '../audio/Narration';
import {Soundtrack,type Cue} from '../audio/Soundtrack';
import {ContentChart} from './UniversalContentShort';

type Line={at:number;text:string;tts?:string};
const C={bg:'#061317',panel:'#0b2429',line:'#29484e',gold:'#f7c84b',cyan:'#18e0d0',white:'#f5fbfa',muted:'#91a9ab'};
const marksFor=(lines:Line[],fps:number,duration:number):VoiceMark[]=>lines.map((line,i)=>({text:line.text,startFrame:Math.round(line.at*fps),endFrame:Math.round(Math.min(lines[i+1]?.at??duration-.2,line.at+10)*fps)}));

export const UniversalContentLong:React.FC<{locale:'vi'|'en'}>=({locale})=>{
  const frame=useCurrentFrame();const {fps,durationInFrames}=useVideoConfig();const sec=frame/fps;const duration=durationInFrames/fps;const p=sec/duration;const chapter=Math.min(5,Math.floor(p*6));const copy=core.locales[locale];const lines=copy.longNarration as Line[];const marks=marksFor(lines,fps,duration);const checks=core.content.lessonChecks[locale];const displayTitle=locale==='en'?(copy.metadata?.title||copy.hook):core.content.title;const displayTopic=locale==='en'?(copy.metadata?.title||copy.hook):core.content.topic;
  const intro=spring({frame,fps,config:{damping:18,stiffness:100}});const cues:Cue[]=Array.from({length:7},(_,i)=>({at:Math.round(i*durationInFrames/6),sound:i===0?'thud':'tick',gain:i===0 ? .38 : .24}));
  return <AbsoluteFill style={{background:C.bg,color:C.white,fontFamily:TEXT_FONT,overflow:'hidden'}}><div style={{position:'absolute',inset:0,background:'radial-gradient(circle at 75% 15%,rgba(24,224,208,.11),transparent 38%),radial-gradient(circle at 10% 90%,rgba(247,200,75,.08),transparent 35%)'}}/>
    <div style={{position:'absolute',left:72,right:72,top:46,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><b style={{fontFamily:DISPLAY_FONT,fontSize:28,color:C.gold}}>{displayTitle}</b><div style={{fontSize:16,color:C.muted,marginTop:6}}>{core.data.symbol} · {core.data.timeframe} · EDUCATIONAL</div></div><div style={{textAlign:'right'}}><b style={{fontSize:24,color:C.cyan}}>{core.longVideo.chapters[locale][chapter]}</b><div style={{fontSize:16,color:C.muted,marginTop:6}}>{Math.floor(sec/60)}:{String(Math.floor(sec%60)).padStart(2,'0')} / {Math.floor(duration/60)}:{String(Math.floor(duration%60)).padStart(2,'0')}</div></div></div>
    <div style={{position:'absolute',top:130,left:72,right:72,height:4,background:'#1d383e'}}><div style={{height:'100%',width:`${p*100}%`,background:`linear-gradient(90deg,${C.gold},${C.cyan})`}}/></div>
    {chapter===0&&<div style={{position:'absolute',inset:'190px 120px 120px',display:'grid',gridTemplateColumns:'1fr 1fr',gap:70,alignItems:'center'}}><div style={{transform:`scale(${intro})`,transformOrigin:'left center'}}><div style={{fontSize:22,color:C.gold,fontWeight:900,letterSpacing:2}}>DEEP DIVE · {Math.round(duration/60)} {locale==='vi'?'PHÚT':'MINUTES'}</div><div style={{fontFamily:DISPLAY_FONT,fontSize:82,lineHeight:1.02,marginTop:24}}>{displayTopic}</div><div style={{fontSize:30,lineHeight:1.45,color:C.muted,marginTop:28}}>{copy.hook}</div></div><div style={{height:620,background:'rgba(8,30,34,.9)',border:`1px solid ${C.line}`,borderRadius:26,padding:18}}><ContentChart frame={Math.round(p*1800)} mode={core.content.type}/></div></div>}
    {chapter>0&&chapter<5&&<div style={{position:'absolute',inset:'170px 90px 100px',display:'grid',gridTemplateColumns:'1.35fr .65fr',gap:38}}><div style={{background:'rgba(8,30,34,.9)',border:`1px solid ${C.line}`,borderRadius:24,padding:18}}><ContentChart frame={Math.round(p*2400)} mode={core.content.type}/></div><div style={{display:'flex',flexDirection:'column',justifyContent:'center',gap:18}}><div style={{fontFamily:DISPLAY_FONT,fontSize:50,lineHeight:1.06}}>{core.longVideo.chapters[locale][chapter]}</div>{checks.map((check,i)=><div key={check} style={{background:C.panel,border:`1px solid ${C.line}`,borderRadius:16,padding:'20px 22px',fontSize:24,lineHeight:1.35,color:i===Math.min(2,chapter-1)?C.white:C.muted}}><b style={{color:C.gold,marginRight:12}}>{i+1}</b>{check}</div>)}<div style={{fontSize:23,lineHeight:1.45,color:C.cyan,marginTop:12}}>{copy.reason}</div></div></div>}
    {chapter===5&&<div style={{position:'absolute',inset:'210px 170px 140px',display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',textAlign:'center',background:'linear-gradient(145deg,#0d3035,#081c20)',border:`2px solid ${C.gold}80`,borderRadius:32,padding:70}}><div style={{fontFamily:DISPLAY_FONT,fontSize:72}}>{locale==='vi'?'Bối cảnh → Cấu trúc → Xác nhận':'Context → Structure → Confirmation'}</div><div style={{fontSize:30,color:C.muted,marginTop:24}}>{locale==='vi'?'Ba lớp trước mọi quyết định. Không có hợp lưu cũng là một dữ kiện.':'Three layers before every decision. Missing confluence is useful information too.'}</div><div style={{display:'flex',gap:16,marginTop:42}}>{['LIKE',core.engagement[locale].button,'COMMENT'].map((x,i)=><b key={x} style={{fontSize:24,color:i===1?C.bg:C.white,background:i===1?C.gold:'transparent',border:`1px solid ${i===1?C.gold:C.cyan}90`,borderRadius:999,padding:'14px 24px'}}>{x}</b>)}</div></div>}
    <Soundtrack bed="dark" cues={cues} durationInFrames={durationInFrames} fps={fps} bedGain={(f)=>core.voice.musicGain*duckAt(marks,f,fps)}/><Narration id={`showcase-long-${locale}`} marks={marks} frame={frame} tone="dark" bottom={70} respectShortSafeArea={false}/>
  </AbsoluteFill>;
};
