/**
 * Bake the woff2 files in public/fonts into src/fontData.ts as data URIs.
 *
 * Fetching a font over a URL at render time is fragile in a way that only shows
 * up on long renders: Remotion opens fresh pages as it goes, each new page
 * re-requests the font, and a request that never answers hangs the delayRender
 * that FontFace.load() holds open — killing the render a thousand frames in
 * while short test renders pass. A data URI has nothing to request.
 *
 * Fonts change roughly never, so the generated file is committed. Re-run this
 * only when swapping a typeface:
 *
 *     node scripts/embed_fonts.mjs
 */
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, join} from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const FACES = [
  {name: 'INTER_WOFF2', file: 'inter-latin.woff2'},
  {name: 'ARCHIVO_WOFF2', file: 'archivo-black-latin.woff2'},
];

const parts = FACES.map(({name, file}) => {
  const b64 = readFileSync(join(root, 'public/fonts', file)).toString('base64');
  console.log(`${file}: ${b64.length} base64 chars`);
  return `export const ${name} =\n  'data:font/woff2;base64,${b64}';\n`;
});

writeFileSync(
  join(root, 'src/fontData.ts'),
  `// GENERATED by scripts/embed_fonts.mjs — do not edit by hand.\n` +
    `// Source files live in public/fonts. See the script for why these are inlined.\n\n` +
    parts.join('\n'),
);

console.log('wrote src/fontData.ts');
