#!/usr/bin/env node
/**
 * Renders a whole day's plan unattended.
 *
 *   node tool/batch.mjs                      # today's plan, 30 videos
 *   node tool/batch.mjs --count 4            # a short run
 *   node tool/batch.mjs --date 2026-07-29    # a specific day's plan
 *   node tool/batch.mjs --workers 2          # renders in parallel
 *   node tool/batch.mjs --dry-run            # print the plan, render nothing
 *
 * Design notes:
 * - One failing job must not take the batch down, so every job is caught and
 *   recorded; the run reports how many succeeded.
 * - Re-running the same date skips finished videos, which makes a crashed or
 *   cancelled batch cheap to resume.
 * - The manifest is the record of what exists and why, including which captions
 *   came from a model and which fell back.
 */

import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { planFor, candlePlan } from './variants.mjs';
import { writeCaption } from './caption.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ENGINE = join(ROOT, 'video-engine');

const args = process.argv.slice(2);
const flag = (n, d) => { const i = args.indexOf(`--${n}`); return i !== -1 && args[i + 1] ? args[i + 1] : d; };
const has = (n) => args.includes(`--${n}`);

const date = flag('date', new Date().toISOString().slice(0, 10));
const count = Number(flag('count', '30'));
const workers = Math.max(1, Number(flag('workers', '1')));
const dryRun = has('dry-run');
// Operational escape hatch: re-run one job after a fix without the whole day.
const only = flag('only', '');
// One format only. `candle-lesson` also switches to the catalogue plan, which is
// the only way to ask for more videos than a single day contains.
const format = flag('format', '');
// The finished file gets its absolute level set once; see
// video-engine/scripts/chuan_am_luong.py for why that is not done in the engine.
const skipLoudness = has('no-loudness');
/**
 * Video quality, as h264's constant-rate factor. Lower is bigger.
 *
 * Remotion defaults to 18, which is a mastering setting: visually lossless and
 * about 5.3 MB for one of these. At 23 the same video is 2.7 MB and, compared
 * frame against frame, indistinguishable — these are flat-coloured charts on a
 * dark ground, which is exactly what h264 compresses well. That matters twice
 * over: a day of thirty is 80 MB instead of 160, and every one of them is going
 * to be re-encoded by YouTube or TikTok on upload anyway, so the extra bitrate
 * was never going to reach a viewer.
 *
 * Pass --crf 18 to get the old masters back.
 */
const crf = flag('crf', '23');

const OUT = join(ENGINE, 'out', 'batch', date);
const MANIFEST = join(OUT, 'manifest.json');
const python = process.platform === 'win32' ? 'python' : 'python3';
const browser = process.env.REMOTION_BROWSER;
// Narration is on when the engine has been installed and not explicitly disabled.
const voiceEnabled =
  !has('no-voice') &&
  ['piper', 'piper.exe'].some((n) => existsSync(join(ENGINE, 'vendor', 'piper', n)));

/**
 * Windows needs a shell here, and that is not negotiable: `npx` is `npx.cmd`,
 * and current Node refuses to spawn a .cmd without one.
 *
 * Node 24 prints a DeprecationWarning about passing an argument array with a
 * shell. It is noise in this context — every argument is generated by this
 * script, none comes from user input — and the alternative was tried and
 * reverted, because naming npx.cmd directly with shell off is exactly the kind
 * of Windows-only change that cannot be verified from here and has already
 * broken this tool twice. A cosmetic warning is not worth that risk.
 */

/**
 * Run a command, streaming its progress out.
 *
 * `onLine` used to be absent and stdout was thrown away entirely, which meant a
 * two-and-a-half minute render printed nothing at all. The console sat frozen
 * and the only reasonable conclusion was that it had crashed — the run was
 * reported as broken when it was working correctly. Silence is not a neutral
 * default for something this slow.
 */
const sh = (cmd, cmdArgs, onLine) =>
  new Promise((res, rej) => {
    const p = spawn(cmd, cmdArgs, { cwd: ENGINE, shell: process.platform === 'win32' });
    let err = '';
    let buf = '';
    p.stderr.on('data', (d) => { err += d.toString(); });
    p.stdout.on('data', (d) => {
      if (!onLine) return;
      buf += d.toString();
      const parts = buf.split(/[\r\n]+/);
      buf = parts.pop() ?? '';
      for (const line of parts) if (line.trim()) onLine(line.trim());
    });
    p.on('close', (code) =>
      code === 0 ? res() : rej(new Error(`${cmd} exited ${code}\n${err.trim().slice(-600)}`)));
    p.on('error', rej);
  });

/** Produce the config for a job and report the facts a caption can use. */
async function buildData(job) {
  if (job.format === 'candle-lesson') {
    const out = `src/data/batch_${job.id}.json`;
    // --stats measures how the pattern actually performed across real history.
    // It needs network; the generator degrades to no stats rather than failing,
    // which keeps this the one format that still works offline.
    await sh(python, ['scripts/make_candle_lesson.py',
      '--pattern', job.pattern, '--seed', String(job.seed), '--out', out, '--stats']);
    const cfg = JSON.parse(readFileSync(join(ENGINE, out), 'utf8'));
    return {
      composition: 'CandleLesson',
      configPath: out,
      cfg,
      facts: { patternName: cfg.pattern.name },
    };
  }

  if (job.format === 'market-map') {
    const out = `src/data/batch_${job.id}.json`;
    // Daily bars need a longer history window to fill the map than hourly do.
    const range = job.interval === '1d' ? '2y' : '3mo';
    await sh(python, ['scripts/make_market_map.py',
      '--symbol', job.symbol, '--pair', job.pair,
      '--interval', job.interval, '--timeframe', job.timeframe,
      '--range', range, '--out', out]);
    const cfg = JSON.parse(readFileSync(join(ENGINE, out), 'utf8'));
    return {
      composition: 'MarketMap',
      configPath: out,
      cfg,
      facts: { bias: cfg.bias, zones: cfg.zones.map((z) => z.label).join(', ') },
    };
  }

  const judge = job.format === 'named-setup' ? 'pattern' : 'channel';
  const out = `src/data/batch_${job.id}.json`;
  await sh(python, ['scripts/fetch_gold.py',
    '--symbol', job.symbol, '--pair', job.pair,
    '--interval', job.interval, '--timeframe', job.timeframe,
    '--range', '60d', '--outcome', job.outcome, '--judge', judge, '--out', out]);

  const cfg = JSON.parse(readFileSync(join(ENGINE, out), 'utf8'));
  const rr = judge === 'pattern' ? cfg.patternTrade : cfg.riskReward;
  const ratio = rr ? Math.abs(rr.target - rr.entry) / Math.max(1e-9, Math.abs(rr.stop - rr.entry)) : null;
  return {
    composition: judge === 'pattern' ? 'LessonShort' : 'XauChart',
    configPath: out,
    cfg,
    facts: {
      side: judge === 'pattern' ? cfg.patternSide : cfg.side,
      entry: rr?.entry,
      rr: ratio ? ratio.toFixed(1) : null,
    },
  };
}

/** Write the model's copy back into the config the renderer reads. */
function applyCaption(cfgPath, cfg, caption, format) {
  // The market map has no model-written line on screen: every word on it is
  // either a measured level or a fixed disclaimer, and inventing copy about
  // levels is how a plan starts sounding like a promise.
  if (format === 'market-map') return;

  if (format === 'candle-lesson') {
    // Only a model's line replaces the generator's.
    //
    // The fallback for this format is `What a <pattern> actually tells you` —
    // one template, filled in a hundred times, which is exactly the sameness the
    // seeded taglines in make_candle_lesson.py exist to break. Overwriting a
    // written line with a generated template is a downgrade, so it does not
    // happen: with no key configured, the generator's own tagline ships.
    if (caption.source !== 'fallback') cfg.pattern.tagline = caption.hook;
  } else {
    cfg.title = caption.title;
    cfg.hook = caption.hook;
  }
  writeFileSync(join(ENGINE, cfgPath), JSON.stringify(cfg, null, 2));
}

async function runJob(job) {
  const target = `out/batch/${date}/${job.id}.mp4`;
  if (existsSync(join(ENGINE, target))) {
    return { ...job, status: 'skipped', file: target, reason: 'already rendered' };
  }

  const started = Date.now();
  const { composition, configPath, cfg, facts } = await buildData(job);
  // The market map carries no model-written line, so it skips the LLM entirely.
  const caption =
    job.format === 'market-map'
      ? { title: `${job.pair} ${job.timeframe} market map`, hook: null, source: 'none' }
      : await writeCaption(job, facts);
  applyCaption(configPath, cfg, caption, job.format);

  // Narration is opt-in and best-effort. The engine is installed per machine by
  // scripts/setup_voice.py; without it the video renders exactly as before, so a
  // missing engine must never fail a job.
  if (voiceEnabled) {
    try {
      await sh(python, ['scripts/make_voice.py', '--config', configPath, '--id', job.id]);
    } catch (err) {
      console.log(`       narration skipped: ${String(err.message ?? err).split('\n')[0]}`);
    }
  }

  let lastTenth = -1;
  await sh(
    'npx',
    ['remotion', 'render', composition, target,
      `--props=./${configPath}`,
      `--crf=${crf}`,
      ...(browser ? [`--browser-executable=${browser}`] : [])],
    (line) => {
      const m = line.match(/Rendered (\d+)\/(\d+)/);
      if (!m) return;
      const tenth = Math.floor((10 * Number(m[1])) / Number(m[2]));
      if (tenth > lastTenth) {
        lastTenth = tenth;
        process.stdout.write(`       ${job.id} ${tenth * 10}%\n`);
      }
    },
  );

  // Level is the last thing done, on the finished file, because integrated
  // loudness is only measurable once every track is in the mix. Skipping it is
  // not fatal: the video is watchable, just quieter than the platform expects.
  let loudness = 'skipped';
  if (!skipLoudness) {
    try {
      await sh(python, ['scripts/chuan_am_luong.py', target], (line) => {
        const m = line.match(/(-?\d+\.\d+)\s*->\s*(-?\d+\.\d+)\s*LUFS/);
        if (m) loudness = `${m[1]} -> ${m[2]} LUFS`;
      });
    } catch (err) {
      loudness = `failed: ${String(err.message ?? err).split('\n')[0]}`;
    }
  }

  return {
    ...job,
    status: 'rendered',
    file: target,
    loudness,
    composition,
    caption: { title: caption.title, hook: caption.hook, source: caption.source },
    renderSeconds: Math.round((Date.now() - started) / 1000),
    // All current batch compositions are 2100 frames at 60 fps. Keep this
    // distinct from wall-clock render time; older manifests called the latter
    // simply `seconds`, which made downstream scheduling reports ambiguous.
    videoDurationSeconds: 35,
  };
}

/** Fixed-size worker pool; each worker pulls the next job until none are left. */
async function pool(jobs, size, fn, onDone) {
  const queue = [...jobs];
  const results = [];
  await Promise.all(
    Array.from({ length: Math.min(size, queue.length) }, async () => {
      for (;;) {
        const job = queue.shift();
        if (!job) return;
        try {
          const r = await fn(job);
          results.push(r);
          onDone(r);
        } catch (err) {
          const r = { ...job, status: 'failed', error: String(err.message ?? err).slice(0, 400) };
          results.push(r);
          onDone(r);
        }
      }
    }),
  );
  return results;
}

/**
 * Fail loudly and early on a machine that cannot finish the job.
 *
 * A batch that dies twenty minutes in because Python is missing wastes the
 * slot it was given. Everything checked here is cheap and checked before the
 * first render starts.
 */
function preflight() {
  const problems = [];

  const major = Number(process.versions.node.split('.')[0]);
  if (major < 18) problems.push(`Node ${process.versions.node} is too old — install Node 18 or newer from https://nodejs.org`);

  const py = spawnSync(python, ['--version'], { encoding: 'utf8' });
  if (py.status !== 0) {
    problems.push(`"${python}" not found — install Python 3 from https://python.org and tick "Add to PATH"`);
  }

  if (!existsSync(join(ENGINE, 'node_modules'))) {
    problems.push('Dependencies are not installed — run:  npm install   inside the video-engine folder');
  }

  // The soundtrack ships as finished WAVs precisely so this machine never needs
  // numpy. If they are missing, every render fails on a missing asset, so say so
  // once here rather than thirty times in a row.
  const missingAudio = ['bed-dark', 'bed-light', 'tick', 'thud', 'whoosh', 'riser', 'win', 'loss']
    .filter((n) => !existsSync(join(ENGINE, 'public', 'audio', `${n}.wav`)));
  if (missingAudio.length) {
    problems.push(
      `Sound files missing from video-engine/public/audio: ${missingAudio.join(', ')}. ` +
        'Re-extract the zip, or regenerate with: python3 scripts/make_audio.py (needs numpy)',
    );
  }

  console.log(
    voiceEnabled
      ? 'Narration: on.\n'
      : 'Narration: off (run  python3 scripts/setup_voice.py  in video-engine to enable).\n',
  );

  if (!process.env.LLM_API_KEY) {
    console.log('Note: no LLM_API_KEY set, so captions use the built-in fallback. The batch still runs.\n');
  }

  if (problems.length) {
    console.error('Cannot start:\n');
    for (const p of problems) console.error(`  - ${p}`);
    console.error('');
    process.exit(1);
  }
}

if (!dryRun) preflight();

let plan = format === 'candle-lesson' ? candlePlan(date, count) : planFor(date, count);
if (format && format !== 'candle-lesson') plan = plan.filter((j) => j.format === format);
if (only) plan = plan.filter((j) => j.id.includes(only));
if (!plan.length) { console.error(`No jobs match --only "${only}".`); process.exit(1); }
console.log(`Plan for ${date}: ${plan.length} videos, ${workers} at a time\n`);

if (dryRun) {
  plan.forEach((j, i) => console.log(`${String(i + 1).padStart(2)}. ${j.format.padEnd(17)} ${j.label}`));
  console.log('\nDry run — nothing rendered.');
  process.exit(0);
}

mkdirSync(OUT, { recursive: true });
const t0 = Date.now();
let done = 0;

const results = await pool(plan, workers, runJob, (r) => {
  done += 1;
  const mark = r.status === 'rendered' ? 'ok' : r.status === 'skipped' ? '--' : 'FAIL';
  const extra = r.status === 'rendered' ? `${r.renderSeconds}s render · ${r.videoDurationSeconds}s video · caption: ${r.caption.source} · ${r.loudness}`
    : r.status === 'failed' ? r.error.split('\n')[0] : r.reason;
  console.log(`[${String(done).padStart(2)}/${plan.length}] ${mark.padEnd(4)} ${r.id.padEnd(30)} ${extra}`);
});

const summary = {
  date,
  finishedAt: new Date().toISOString(),
  minutes: Math.round((Date.now() - t0) / 60_000),
  rendered: results.filter((r) => r.status === 'rendered').length,
  skipped: results.filter((r) => r.status === 'skipped').length,
  failed: results.filter((r) => r.status === 'failed').length,
  videos: results,
};
writeFileSync(MANIFEST, JSON.stringify(summary, null, 2));

console.log(`\n${summary.rendered} rendered, ${summary.skipped} skipped, ${summary.failed} failed in ${summary.minutes} min`);
console.log(`Videos:   ${OUT}`);
console.log(`Manifest: ${MANIFEST}`);
if (summary.failed) process.exitCode = 1;
